### ISSUE TITLE
Main UI Callback Error

### ISSUE THREAD

**Issue by opengrip** [rootdarkarchon/XIVJitterFix#2]
Its giving me a warning that the plugin does not register a main UI callback. 
"If your plugin has a window that could be considered the main entrypoint to its features, please consider registering UiBuilder.OpenMainUi to open the plugins main window. "

I'm not exactly sure what this means or if its preventing the function of the plugin but I figured I would report it just incase. 

![image_2024-07-03_021401541](https://github.com/rootdarkarchon/XIVJitterFix/assets/95540448/d2b8de08-dedf-497c-9e20-49fc56804963)

**Comment by rootdarkarchon** [comment]
It has no main UI so this is expected and perfectly fine.
