### ISSUE TITLE
toggle to "Ignore Downscaling"

### ISSUE THREAD

**Issue by Crescr** [rootdarkarchon/XIVJitterFix#4]
Disable → Enable: The downscale state returns to the original resolution. (It is functioning)

Enable → Disable: Does not return to downscale state. (Not functioning) *1

If you uncheck it and switch to FSR once, then switch to DLSS again, it will return to the original downscale state.
*I would like you to correct 1.

**Comment by rootdarkarchon** [comment]
🤷‍♂️ I'm only setting a flag, if the renderer doesn't respect that flag after changing it I can't do much about it.
Stop fucking around with it. Set it and forget it.
