### ISSUE TITLE
Bug : Version 0.3 force DLAA

### ISSUE THREAD

**Issue by Guilhem30** [rootdarkarchon/XIVJitterFix#5]
I'm using DLSSTweaks to force DLSS to quality but since I updated to version 0.3 it forces DLAA when the game boot.
I have the ignore downscaling option unchecked.
This happens on every start of the game and the only way to use DLSS is to switch to FSR and back to DLSS or to downgrade the plugin to 0.2.

**Comment by rootdarkarchon** [comment]
I cannot reproduce this. On the title screen it will use DLAA or DLAA-esque, once in-game the game uses DLSS scaled as expected via dlsstweaks. Can you show me your dlsstweaks.ini?
Can you check if it actually uses DLAA in-game by using `OverrideDlssHud=1` in the dlsstweaks config?

**Comment by Guilhem30** [comment]
I get this while ingame : 
![image](https://github.com/rootdarkarchon/XIVJitterFix/assets/4310646/317310a2-0b5b-41d4-a399-9ce1563b64a5)


So not actual DLAA but DLSS with a resolution lower by a couple pixels, it's not taking into account my quality level unless I enable FSR and switch back to DLSS.
I'm using a beta version of dlsstweak that fix a similar issue happening in xiv when not using XIVJitterFix

Here is my ini file :
[dlsstweaks.ini](https://github.com/user-attachments/files/16159601/dlsstweaks.ini.txt)

Edit : Actually it's not the same issue as when not using the beta version of DLSStweak because with it DLSS is not working at all when getting ingame

**Comment by rootdarkarchon** [comment]
Hm, I cannot reproduce this at all. What are your ingame settings for graphics? If the toggle is set to off it should always force downscaling to on.

**Comment by rootdarkarchon** [comment]
so my dlsstweaks config is as follows (I do not use the nexusmods dlss implementation but just copied dlsstweaks on its own and ran the registry tweak to be able to load unregistered nvngx.dll)

[DLSS]
ForceDLAA=false
OverrideAutoExposure=1
OverrideSharpening=1.0
OverrideDlssHud=1
DisableDevWatermark=true
VerboseLogging=false

[DLLPathOverrides]

[DLSSQualityLevels]
Enable=true
UltraPerformance=0.25
Performance=0.5
Balanced=0.5
Quality=0.66
UltraQuality=0.77

[DLSSPresets]
DLAA=F
UltraPerformance=F
Performance=E
Balanced=E
Quality=E
UltraQuality=E

[Compatibility]
ResolutionOffset=0
DynamicResolutionOverride=true
DynamicResolutionMinOffset=-1
DisableIniMonitoring=false
OverrideAppId=false

[DLSSTweaks]

Ingame setting like so:
![image](https://github.com/rootdarkarchon/XIVJitterFix/assets/21534284/60b29990-1559-4767-b4d8-a5271d78d3be)

On title screen:
![image](https://github.com/rootdarkarchon/XIVJitterFix/assets/21534284/e630fccb-d432-426b-8a08-f5e06f62d28f)

After logging into the game:
![image](https://github.com/rootdarkarchon/XIVJitterFix/assets/21534284/3b25a8f4-6d4f-481e-864d-dbe19a3875a6)

Jitterfix config is "Ignore Downscaling" disabled.

**Comment by rootdarkarchon** [comment]
I see, the issue appears if you don't have DLSS set to "Always Enabled" but only "Below 30/60 fps"

**Comment by rootdarkarchon** [comment]
However, I want to emphasize that I can reliably reproduce this exact issue with XIVJitterFix completely unloaded from Dalamud.

This appears to be an in-engine "issue", or something caused by the dlsstweaks settings.
Setting the Frame Rate Threshold to "Below 30/60 fps" will launch the game without forcing DLSS to the quality option as desired.

This does not seem to be related to XIVJitterFix' "Ignore Downscale" option whatsoever.

Use "Always Enabled" for Frame Rate Threshold to force DLSS to be running at your desired quality setting.

**Comment by Guilhem30** [comment]
I already had the "Always Enabled" setting chosen but I did more tests and it appears that the bug is caused by a combination of the beta version of dlsstweaks recommended for xiv on nexusmods and this plugin. I doesn't happen with the stable version of dlsstweaks or without the plugin.

**Comment by rootdarkarchon** [comment]
This makes absolutely no sense unless there's some fuckery going on with the DLSS implementation. It should always behave the same? I did not test against the beta of dlsstweaks, nor do I plan to. Dunno how this is related to DLSS at all, could be weird interop between dlsstweaks and the xiv engine.
Whatever, I'll release 0.0.0.4 on Dalamud with a toggle to ignore overriding settings then the tool will do absolutely nothing if the override is not switched on.

**Comment by Guilhem30** [comment]
I can confirm that the updated version with the new checkbox fixes my issue, thank you
