### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by kek-dev** [rootdarkarchon/XIVJitterFix#6]
First of all thank you for this great mod!

Is it possible to make this mod compatible with DLSS mods such as https://www.nexusmods.com/finalfantasy14/mods/2199?tab=description (I'm using this mod to set up scaling and disable dynamic resolution) but when I enable both jittefix and this mod from nexusmods my game just crashes :<

I tried to look for some logs but couldn't find any, if I can provide anything to resolve this then just tell me ^^

**Comment by rootdarkarchon** [comment]
Use the original dlsstweaks which works perfectly fine. I don't know what this mod does and why it differs so much from the original dlsstweaks that it doesn't work.
