### ISSUE TITLE
Tracking FF XIV jitter defect

### ISSUE THREAD

**Issue by MikeZTM** [rootdarkarchon/XIVJitterFix#8]
Since this plugin fix a critical defect within the implementation of DLSS for FF XIV 7.0. Do we have a tracker for each game patch release to see if the game itself fixes this defect?
I don't know if this is the correct place to ask this, but I just can't find any information about jitter defect and 7.1 patch.

**Comment by rootdarkarchon** [comment]
It's fixed through the game and the development for this has no purpose anymore.
